/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSmilekeysRouteImport } from './routes/admin.smilekeys'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AdminNewsIndexRouteImport } from './routes/admin.news.index'
import { Route as AdminNewsArticleIdRouteImport } from './routes/admin.news.$articleId'
import { Route as AdminNewsNewRouteImport } from './routes/admin.news.new'
import { Route as AdminPlayersIndexRouteImport } from './routes/admin.players.index'
import { Route as AdminPlayersNameRouteImport } from './routes/admin.players.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmilekeysRoute = AdminSmilekeysRouteImport.update({
  id: '/smilekeys',
  path: '/smilekeys',
  getParentRoute: () => AdminRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsArticleIdRoute = AdminNewsArticleIdRouteImport.update({
  id: '/news/$articleId',
  path: '/news/$articleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersIndexRoute = AdminPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersNameRoute = AdminPlayersNameRouteImport.update({
  id: '/players/$name',
  path: '/players/$name',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smilekeys': typeof AdminSmilekeysRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/news/$articleId': typeof AdminNewsArticleIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$name': typeof AdminPlayersNameRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smilekeys': typeof AdminSmilekeysRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/admin/news/$articleId': typeof AdminNewsArticleIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$name': typeof AdminPlayersNameRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/players': typeof AdminPlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smilekeys': typeof AdminSmilekeysRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/news/$articleId': typeof AdminNewsArticleIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/players/$name': typeof AdminPlayersNameRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/register'
    | '/signin'
    | '/admin/settings'
    | '/admin/smilekeys'
    | '/news/$slug'
    | '/admin/'
    | '/news/'
    | '/admin/news/$articleId'
    | '/admin/news/new'
    | '/admin/players/$name'
    | '/admin/news/'
    | '/admin/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/register'
    | '/signin'
    | '/admin/settings'
    | '/admin/smilekeys'
    | '/news/$slug'
    | '/admin'
    | '/news'
    | '/admin/news/$articleId'
    | '/admin/news/new'
    | '/admin/players/$name'
    | '/admin/news'
    | '/admin/players'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/register'
    | '/signin'
    | '/admin/settings'
    | '/admin/smilekeys'
    | '/news/$slug'
    | '/admin/'
    | '/news/'
    | '/admin/news/$articleId'
    | '/admin/news/new'
    | '/admin/players/$name'
    | '/admin/news/'
    | '/admin/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smilekeys': {
      id: '/admin/smilekeys'
      path: '/smilekeys'
      fullPath: '/admin/smilekeys'
      preLoaderRoute: typeof AdminSmilekeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$articleId': {
      id: '/admin/news/$articleId'
      path: '/news/$articleId'
      fullPath: '/admin/news/$articleId'
      preLoaderRoute: typeof AdminNewsArticleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players/': {
      id: '/admin/players/'
      path: '/players'
      fullPath: '/admin/players/'
      preLoaderRoute: typeof AdminPlayersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players/$name': {
      id: '/admin/players/$name'
      path: '/players/$name'
      fullPath: '/admin/players/$name'
      preLoaderRoute: typeof AdminPlayersNameRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmilekeysRoute: typeof AdminSmilekeysRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminNewsArticleIdRoute: typeof AdminNewsArticleIdRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminPlayersNameRoute: typeof AdminPlayersNameRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminPlayersIndexRoute: typeof AdminPlayersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmilekeysRoute: AdminSmilekeysRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminNewsArticleIdRoute: AdminNewsArticleIdRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminPlayersNameRoute: AdminPlayersNameRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminPlayersIndexRoute: AdminPlayersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
